name: 'election_analysis'
version: '1.0.0'
config-version: 2

profile: 'election_project'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  election_analysis:  # 或其他適合你項目的名稱
    +materialized: view

